flowchart TD
    A-->B

    
%% update node/edge name
%% add new node/edge
%% delete node/edge

%% Create a new  project and select a node from the graph
%% Create a new project but can not find suitable nodes, choose root node
%% Create a new project with completely different purpose.    

